### PR TITLE
bump patch

### PR DESCRIPTION
**Pull request by t-bltg**
For https://github.com/aminya/CompileBot.jl/pull/54.

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
Some of the jobs fail. They don't accept this version range

**Comment by t-bltg** [comment]
Ha, ranges are `1.6`, sorry. Will revert.

**Comment by aminya** [comment]
No worries. Thank you

**Comment by t-bltg** [comment]
Could you register the new version though ?

**Comment by aminya** [comment]
Yes. Here you go
https://github.com/JuliaRegistries/General/pull/65678?notification_referrer_id=NT_kwDOAPqFlbM0MTM2MTA1NjM2OjE2NDE4MTk3

**Comment by t-bltg** [comment]
Thanks !

**Pull request closed without merging**
